<?php
$iPhone ='{"iPhone 2G": "iPhone1,1",
    "iPhone 3G": "iPhone1,2",
    "iPhone 3G[S]": "iPhone2,1",
    "iPhone 4 (GSM)": "iPhone3,1",
    "iPhone 4 (GSM \/ 2012)": "iPhone3,2",
    "iPhone 4 (CDMA)": "iPhone3,3",
    "iPhone 4[S]": "iPhone4,1",
    "iPhone 5 (GSM)": "iPhone5,1",
    "iPhone 5 (Global)": "iPhone5,2",
    "iPhone 5c (GSM)": "iPhone5,3",
    "iPhone 5c (Global)": "iPhone5,4",
    "iPhone 5s (GSM)": "iPhone6,1",
    "iPhone 5s (Global)": "iPhone6,2",
    "iPhone 6+": "iPhone7,1",
    "iPhone 6": "iPhone7,2",
    "iPhone 6s": "iPhone8,1",
    "iPhone 6s+": "iPhone8,2",
    "iPhone SE": "iPhone8,4",
    "iPhone 7 (Global)": "iPhone9,1",
    "iPhone 7 Plus (Global)": "iPhone9,2",
    "iPhone 7 (GSM)": "iPhone9,3",
    "iPhone 7 Plus (GSM)": "iPhone9,4"
    }';
$iPad = '{"iPad 1": "iPad1,1",
    "iPad 2 (WiFi)": "iPad2,1",
    "iPad 2 (GSM)": "iPad2,2",
    "iPad 2 (CDMA)": "iPad2,3",
    "iPad 2 (Mid 2012)": "iPad2,4",
    "iPad Mini (WiFi)": "iPad2,5",
    "iPad Mini (GSM)": "iPad2,6",
    "iPad Mini (Global)": "iPad2,7",
    "iPad 3 (WiFi)": "iPad3,1",
    "iPad 3 (CDMA)": "iPad3,2",
    "iPad 3 (GSM)": "iPad3,3",
    "iPad 4 (WiFi)": "iPad3,4",
    "iPad 4 (GSM)": "iPad3,5",
    "iPad 4 (Global)": "iPad3,6",
    "iPad Air (WiFi)": "iPad4,1",
    "iPad Air (Cellular)": "iPad4,2",
    "iPad Air (China)": "iPad4,3",
    "iPad Mini 2 (WiFi)": "iPad4,4",
    "iPad Mini 2 (Cellular)": "iPad4,5",
    "iPad Mini 2 (China)": "iPad4,6",
    "iPad Mini 3 (WiFi)": "iPad4,7",
    "iPad Mini 3 (Cellular)": "iPad4,8",
    "iPad Mini 3 (China)": "iPad4,9",
    "iPad Mini 4 (WiFi)": "iPad5,1",
    "iPad Mini 4 (Cellular)": "iPad5,2",
    "iPad Air 2 (WiFi)": "iPad5,3",
    "iPad Air 2 (Cellular)": "iPad5,4",
    "iPad Pro 9.7-inch (WiFi)": "iPad6,3",
    "iPad Pro 9.7-inch (Cellular)": "iPad6,4",
    "iPad Pro 12.9-inch (WiFi)": "iPad6,7",
    "iPad Pro 12.9-inch (Cellular)": "iPad6,8"}';
    $iPod = '{"iPod touch 1G": "iPod1,1",
    "iPod touch 2G": "iPod2,1",
    "iPod touch 3": "iPod3,1",
    "iPod touch 4": "iPod4,1",
    "iPod touch 5": "iPod5,1",
    "iPod touch 6": "iPod7,1"}';
    $AppleTV = '{"Apple TV 2G": "AppleTV2,1",
    "Apple TV 3": "AppleTV3,1",
    "Apple TV 3 (2013)": "AppleTV3,2",
    "Apple TV 4 (2015)": "AppleTV5,3"}';
    $devices['iPhone'] = json_decode($iPhone,true);
    $devices['iPod'] = json_decode($iPod,true);
    $devices['iPad'] = json_decode($iPad,true);
    $devices['AppleTV'] = json_decode($AppleTV,true);
echo json_encode($devices, JSON_PRETTY_PRINT);
